In [ ]:
from google.colab import drive
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive')

# Define file path in Google Drive
file_path = "/content/drive/My Drive/cleaned_encoded.csv"
df=pd.read_csv(file_path)

Mounted at /content/drive

In [ ]:
df

,Location,MinimumTemperature,MaximumTemperature,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,CloudBurstTomorrow,Year,Month,Day,WindGustDirection_sin,WindGustDirection_cos,WindDirection9am_sin,WindDirection9am_cos,WindDirection3pm_sin,WindDirection3pm_cos
0,0.203289,13.4,22.900000,0.6,5.318667,7.611178,44.000000,20.0,24.0,71.0,...,0,2008,12,1,-1.000000,-1.836970e-16,-1.000000,-1.836970e-16,-0.923880,3.826834e-01
1,0.203289,7.4,25.100000,0.0,5.318667,7.611178,44.000000,4.0,22.0,44.0,...,0,2008,12,2,-0.923880,3.826834e-01,-0.382683,9.238795e-01,-0.923880,-3.826834e-01
2,0.203289,12.9,25.700000,0.0,5.318667,7.611178,46.000000,19.0,26.0,38.0,...,0,2008,12,3,-0.923880,-3.826834e-01,-1.000000,-1.836970e-16,-0.923880,-3.826834e-01
3,0.203289,9.2,28.000000,0.0,5.318667,7.611178,24.000000,11.0,9.0,45.0,...,0,2008,12,4,0.707107,7.071068e-01,0.707107,-7.071068e-01,1.000000,6.123234e-17
4,0.203289,17.5,32.300000,1.0,5.318667,7.611178,41.000000,7.0,20.0,82.0,...,0,2008,12,5,-1.000000,-1.836970e-16,0.923880,3.826834e-01,-0.707107,7.071068e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,0.073511,2.8,23.400000,0.0,5.318667,7.611178,31.000000,13.0,11.0,51.0,...,0,2017,6,21,1.000000,6.123234e-17,0.707107,-7.071068e-01,0.923880,3.826834e-01
145456,0.073511,3.6,25.300000,0.0,5.318667,7.611178,22.000000,13.0,9.0,56.0,...,0,2017,6,22,-0.382683,9.238795e-01,0.707107,-7.071068e-01,0.000000,1.000000e+00
145457,0.073511,5.4,26.900000,0.0,5.318667,7.611178,37.000000,9.0,9.0,53.0,...,0,2017,6,23,0.000000,1.000000e+00,0.707107,-7.071068e-01,-0.923880,3.826834e-01
145458,0.073511,7.8,27.000000,0.0,5.318667,7.611178,28.000000,13.0,7.0,51.0,...,0,2017,6,24,0.707107,-7.071068e-01,0.382683,-9.238795e-01,0.000000,1.000000e+00
145459,0.073511,14.9,23.224781,0.0,5.318667,7.611178,39.837792,17.0,17.0,62.0,...,0,2017,6,25,-1.000000,-1.836970e-16,0.923880,-3.826834e-01,0.923880,-3.826834e-01

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# Separate features and target
X = df.drop('CloudBurstTomorrow', axis=1)
y = df['CloudBurstTomorrow']

# Initialize scaler
scaler = MinMaxScaler()

# Fit and transform features
X_scaled = scaler.fit_transform(X)

# Convert back to DataFrame (optional but useful)
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

In [ ]:
df

,Location,MinimumTemperature,MaximumTemperature,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,CloudBurstTomorrow,Year,Month,Day,WindGustDirection_sin,WindGustDirection_cos,WindDirection9am_sin,WindDirection9am_cos,WindDirection3pm_sin,WindDirection3pm_cos
0,0.203289,13.4,22.900000,0.6,5.318667,7.611178,44.000000,20.0,24.0,71.0,...,0,2008,12,1,-1.000000,-1.836970e-16,-1.000000,-1.836970e-16,-0.923880,3.826834e-01
1,0.203289,7.4,25.100000,0.0,5.318667,7.611178,44.000000,4.0,22.0,44.0,...,0,2008,12,2,-0.923880,3.826834e-01,-0.382683,9.238795e-01,-0.923880,-3.826834e-01
2,0.203289,12.9,25.700000,0.0,5.318667,7.611178,46.000000,19.0,26.0,38.0,...,0,2008,12,3,-0.923880,-3.826834e-01,-1.000000,-1.836970e-16,-0.923880,-3.826834e-01
3,0.203289,9.2,28.000000,0.0,5.318667,7.611178,24.000000,11.0,9.0,45.0,...,0,2008,12,4,0.707107,7.071068e-01,0.707107,-7.071068e-01,1.000000,6.123234e-17
4,0.203289,17.5,32.300000,1.0,5.318667,7.611178,41.000000,7.0,20.0,82.0,...,0,2008,12,5,-1.000000,-1.836970e-16,0.923880,3.826834e-01,-0.707107,7.071068e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,0.073511,2.8,23.400000,0.0,5.318667,7.611178,31.000000,13.0,11.0,51.0,...,0,2017,6,21,1.000000,6.123234e-17,0.707107,-7.071068e-01,0.923880,3.826834e-01
145456,0.073511,3.6,25.300000,0.0,5.318667,7.611178,22.000000,13.0,9.0,56.0,...,0,2017,6,22,-0.382683,9.238795e-01,0.707107,-7.071068e-01,0.000000,1.000000e+00
145457,0.073511,5.4,26.900000,0.0,5.318667,7.611178,37.000000,9.0,9.0,53.0,...,0,2017,6,23,0.000000,1.000000e+00,0.707107,-7.071068e-01,-0.923880,3.826834e-01
145458,0.073511,7.8,27.000000,0.0,5.318667,7.611178,28.000000,13.0,7.0,51.0,...,0,2017,6,24,0.707107,-7.071068e-01,0.382683,-9.238795e-01,0.000000,1.000000e+00
145459,0.073511,14.9,23.224781,0.0,5.318667,7.611178,39.837792,17.0,17.0,62.0,...,0,2017,6,25,-1.000000,-1.836970e-16,0.923880,-3.826834e-01,0.923880,-3.826834e-01

In [ ]:
X_scaled_df.describe()

,Location,MinimumTemperature,MaximumTemperature,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,CloudBurst Today,Year,Month,Day,WindGustDirection_sin,WindGustDirection_cos,WindDirection9am_sin,WindDirection9am_cos,WindDirection3pm_sin,WindDirection3pm_cos
count,145460.000000,145460.000000,145460.000000,145460.000000,145460.000000,145460.000000,145460.000000,145460.000000,145460.000000,145460.000000,...,145460.000000,145460.000000,145460.000000,145460.000000,145460.000000,145460.000000,145460.000000,145460.000000,145460.000000,145460.000000
mean,0.512218,0.498470,0.503068,0.261731,0.564741,0.446490,0.520040,0.377063,0.458621,0.621141,...,0.219167,0.576975,0.490874,0.490409,0.455353,0.477586,0.507411,0.542747,0.500914,0.466567
std,0.215363,0.174848,0.173225,0.404038,0.299857,0.318414,0.202911,0.231225,0.208449,0.228093,...,0.413683,0.253768,0.311569,0.293160,0.365279,0.337753,0.334232,0.369336,0.355617,0.349885
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.396718,0.375000,0.375000,0.000000,0.375000,0.375000,0.375000,0.189189,0.320988,0.475610,...,0.000000,0.400000,0.181818,0.233333,0.038060,0.146447,0.146447,0.146447,0.146447,0.146447
50%,0.505039,0.495879,0.490196,0.000000,0.625000,0.375000,0.508333,0.351351,0.458621,0.621951,...,0.000000,0.600000,0.454545,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000
75%,0.672903,0.625000,0.625000,0.400000,0.625000,0.625000,0.625000,0.513514,0.592593,0.792683,...,0.000000,0.800000,0.727273,0.733333,0.853553,0.853553,0.853553,0.961940,0.853553,0.853553
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
from sklearn.model_selection import train_test_split

# Use the scaled data and original labels
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, stratify=y, random_state=42)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

# Define the ANN model
model1 = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  # First hidden layer
    Dense(32, activation='relu'),                                   # Second hidden layer
    Dense(1, activation='sigmoid')                                  # Output layer
])

# Compile the model
model1.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Early stopping to avoid overfitting and restore best weights
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

# Train the model
history1 = model1.fit(
    X_train, y_train,
    epochs=75,                      # Give model room to improve
    batch_size=64,
    validation_split=0.2,

    verbose=1
)

Epoch 1/75

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8189 - loss: 0.4118 - val_accuracy: 0.8435 - val_loss: 0.3613
Epoch 2/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8390 - loss: 0.3671 - val_accuracy: 0.8484 - val_loss: 0.3560
Epoch 3/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8446 - loss: 0.3580 - val_accuracy: 0.8473 - val_loss: 0.3524
Epoch 4/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8459 - loss: 0.3537 - val_accuracy: 0.8514 - val_loss: 0.3480
Epoch 5/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8475 - loss: 0.3524 - val_accuracy: 0.8489 - val_loss: 0.3527
Epoch 6/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8490 - loss: 0.3490 - val_accuracy: 0.8496 - val_loss: 0.3491
Epoch 7/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8499 - loss: 0.3483 - val_accuracy: 0.8518 - val_loss: 0.3458
Epoch 8/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8477 - loss: 0.3482 - val_accuracy: 0.8475 - val_loss: 0.3501
Epoch 9/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8503 - loss: 0.3442 - val_accuracy: 0.8495 - val_loss: 0.3466
Epoch 10/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8510 - loss: 0.3418 - val_accuracy: 0.8525 - val_loss: 0.3429
Epoch 11/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8515 - loss: 0.3437 - val_accuracy: 0.8538 - val_loss: 0.3416
Epoch 12/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8505 - loss: 0.3430 - val_accuracy: 0.8521 - val_loss: 0.3463
Epoch 13/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8489 - loss: 0.3454 - val_accuracy: 0.8532 - val_loss: 0.3419
Epoch 14/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8521 - loss: 0.3410 - val_accuracy: 0.8533 - val_loss: 0.3440
Epoch 15/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8516 - loss: 0.3396 - val_accuracy: 0.8516 - val_loss: 0.3411
Epoch 16/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8502 - loss: 0.3405 - val_accuracy: 0.8529 - val_loss: 0.3408
Epoch 17/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.8543 - loss: 0.3379 - val_accuracy: 0.8522 - val_loss: 0.3427
Epoch 18/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8508 - loss: 0.3410 - val_accuracy: 0.8525 - val_loss: 0.3384
Epoch 19/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8520 - loss: 0.3363 - val_accuracy: 0.8538 - val_loss: 0.3412
Epoch 20/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8539 - loss: 0.3360 - val_accuracy: 0.8549 - val_loss: 0.3389
Epoch 21/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8520 - loss: 0.3382 - val_accuracy: 0.8543 - val_loss: 0.3390
Epoch 22/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.8544 - loss: 0.3328 - val_accuracy: 0.8527 - val_loss: 0.3454
Epoch 23/75
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8528 - loss: 0.3365 - val_accuracy: 0.8532 - val_loss: 0.3406

In [ ]:
model_20 = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])
model_20.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history_20 = model_20.fit(
    X_train, y_train,
    epochs=20,
    batch_size=64,
    validation_split=0.2,

    verbose=1
)

Epoch 1/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8119 - loss: 0.4208 - val_accuracy: 0.8421 - val_loss: 0.3630
Epoch 2/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8420 - loss: 0.3626 - val_accuracy: 0.8315 - val_loss: 0.3885
Epoch 3/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8438 - loss: 0.3591 - val_accuracy: 0.8488 - val_loss: 0.3499
Epoch 4/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8456 - loss: 0.3520 - val_accuracy: 0.8482 - val_loss: 0.3492
Epoch 5/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8481 - loss: 0.3478 - val_accuracy: 0.8504 - val_loss: 0.3457
Epoch 6/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8474 - loss: 0.3490 - val_accuracy: 0.8514 - val_loss: 0.3452
Epoch 7/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8477 - loss: 0.3488 - val_accuracy: 0.8499 - val_loss: 0.3455
Epoch 8/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8471 - loss: 0.3511 - val_accuracy: 0.8508 - val_loss: 0.3450
Epoch 9/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8501 - loss: 0.3420 - val_accuracy: 0.8522 - val_loss: 0.3427
Epoch 10/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8490 - loss: 0.3464 - val_accuracy: 0.8498 - val_loss: 0.3442
Epoch 11/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8500 - loss: 0.3430 - val_accuracy: 0.8512 - val_loss: 0.3435
Epoch 12/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8514 - loss: 0.3428 - val_accuracy: 0.8502 - val_loss: 0.3423
Epoch 13/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8502 - loss: 0.3420 - val_accuracy: 0.8516 - val_loss: 0.3429
Epoch 14/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8525 - loss: 0.3409 - val_accuracy: 0.8489 - val_loss: 0.3447
Epoch 15/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8538 - loss: 0.3393 - val_accuracy: 0.8551 - val_loss: 0.3408
Epoch 16/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8536 - loss: 0.3379 - val_accuracy: 0.8531 - val_loss: 0.3407
Epoch 17/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8545 - loss: 0.3361 - val_accuracy: 0.8525 - val_loss: 0.3398
Epoch 18/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8525 - loss: 0.3376 - val_accuracy: 0.8531 - val_loss: 0.3391
Epoch 19/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8543 - loss: 0.3370 - val_accuracy: 0.8511 - val_loss: 0.3418
Epoch 20/20
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8551 - loss: 0.3361 - val_accuracy: 0.8535 - val_loss: 0.3416

In [ ]:
model_50 = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])
model_50.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history_50 = model_50.fit(
    X_train, y_train,
    epochs=50,
    batch_size=64,
    validation_split=0.2,

    verbose=1
)

Epoch 1/50

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8200 - loss: 0.4049 - val_accuracy: 0.8457 - val_loss: 0.3594
Epoch 2/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8397 - loss: 0.3650 - val_accuracy: 0.8489 - val_loss: 0.3532
Epoch 3/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.8457 - loss: 0.3567 - val_accuracy: 0.8390 - val_loss: 0.3646
Epoch 4/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8470 - loss: 0.3507 - val_accuracy: 0.8412 - val_loss: 0.3615
Epoch 5/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.8464 - loss: 0.3523 - val_accuracy: 0.8485 - val_loss: 0.3543
Epoch 6/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8466 - loss: 0.3511 - val_accuracy: 0.8466 - val_loss: 0.3516
Epoch 7/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.8486 - loss: 0.3465 - val_accuracy: 0.8528 - val_loss: 0.3444
Epoch 8/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8480 - loss: 0.3474 - val_accuracy: 0.8479 - val_loss: 0.3486
Epoch 9/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8470 - loss: 0.3483 - val_accuracy: 0.8532 - val_loss: 0.3429
Epoch 10/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8495 - loss: 0.3471 - val_accuracy: 0.8518 - val_loss: 0.3436
Epoch 11/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8506 - loss: 0.3398 - val_accuracy: 0.8523 - val_loss: 0.3431
Epoch 12/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8509 - loss: 0.3428 - val_accuracy: 0.8514 - val_loss: 0.3417
Epoch 13/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8504 - loss: 0.3425 - val_accuracy: 0.8522 - val_loss: 0.3421
Epoch 14/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8516 - loss: 0.3401 - val_accuracy: 0.8523 - val_loss: 0.3411
Epoch 15/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8513 - loss: 0.3405 - val_accuracy: 0.8534 - val_loss: 0.3401
Epoch 16/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8520 - loss: 0.3398 - val_accuracy: 0.8525 - val_loss: 0.3395
Epoch 17/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8533 - loss: 0.3363 - val_accuracy: 0.8492 - val_loss: 0.3474
Epoch 18/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8515 - loss: 0.3399 - val_accuracy: 0.8511 - val_loss: 0.3421
Epoch 19/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8519 - loss: 0.3382 - val_accuracy: 0.8500 - val_loss: 0.3435
Epoch 20/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.8528 - loss: 0.3374 - val_accuracy: 0.8521 - val_loss: 0.3404
Epoch 21/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8551 - loss: 0.3348 - val_accuracy: 0.8540 - val_loss: 0.3375
Epoch 22/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8560 - loss: 0.3324 - val_accuracy: 0.8536 - val_loss: 0.3375
Epoch 23/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8572 - loss: 0.3314 - val_accuracy: 0.8537 - val_loss: 0.3375
Epoch 24/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8527 - loss: 0.3360 - val_accuracy: 0.8534 - val_loss: 0.3379
Epoch 25/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8534 - loss: 0.3340 - val_accuracy: 0.8524 - val_loss: 0.3380
Epoch 26/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8563 - loss: 0.3297 - val_accuracy: 0.8489 - val_loss: 0.3443
Epoch 27/50
1455/1455 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8548 - loss: 0.3327 - val_accuracy: 0.8529 - val_loss: 0.3394

In [ ]:
from sklearn.metrics import classification_report

# Model A (20 epochs) Evaluation
test_loss_20, test_acc_20 = model_20.evaluate(X_test, y_test, verbose=0)
y_pred_20 = (model_20.predict(X_test) > 0.5).astype(int)  # Convert predictions to binary
print(f"Model A (20 epochs) - Test Accuracy: {test_acc_20:.4f}")
print("Classification Report for Model A (20 epochs):")
print(classification_report(y_test, y_pred_20))

910/910 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
Model A (20 epochs) - Test Accuracy: 0.8544
Classification Report for Model A (20 epochs):
              precision    recall  f1-score   support

           0       0.88      0.94      0.91     22717
           1       0.73      0.53      0.62      6375

    accuracy                           0.85     29092
   macro avg       0.80      0.74      0.76     29092
weighted avg       0.85      0.85      0.85     29092

In [ ]:
# Model B (50 epochs) Evaluation
test_loss_50, test_acc_50 = model_50.evaluate(X_test, y_test, verbose=0)
y_pred_50 = (model_50.predict(X_test) > 0.5).astype(int)  # Convert predictions to binary
print(f"Model B (50 epochs[27]) - Test Accuracy: {test_acc_50:.4f}")
print("Classification Report for Model B (50 epochs):")
print(classification_report(y_test, y_pred_50))

910/910 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
Model B (50 epochs[27]) - Test Accuracy: 0.8570
Classification Report for Model B (50 epochs):
              precision    recall  f1-score   support

           0       0.88      0.95      0.91     22717
           1       0.74      0.53      0.62      6375

    accuracy                           0.86     29092
   macro avg       0.81      0.74      0.77     29092
weighted avg       0.85      0.86      0.85     29092

In [ ]:
# Model C (75 epochs) Evaluation
test_loss_75, test_acc_75 = model1.evaluate(X_test, y_test, verbose=0)
y_pred_75 = (model1.predict(X_test) > 0.5).astype(int)  # Convert predictions to binary
print(f"Model C (75 epochs[23]) - Test Accuracy: {test_acc_75:.4f}")
print("Classification Report for Model C (75 epochs):")
print(classification_report(y_test, y_pred_75))

910/910 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step
Model C (75 epochs[23]) - Test Accuracy: 0.8536
Classification Report for Model C (75 epochs):
              precision    recall  f1-score   support

           0       0.87      0.95      0.91     22717
           1       0.74      0.51      0.60      6375

    accuracy                           0.85     29092
   macro avg       0.81      0.73      0.76     29092
weighted avg       0.84      0.85      0.84     29092

In [ ]:
#---------------------------------------------------dont give code below this--------------------------------------------------------

In [ ]:
# Separate the dataset into two parts: Class 0 and Class 1
class_0 = df[df['CloudBurstTomorrow'] == 0]
class_1 = df[df['CloudBurstTomorrow'] == 1]

# Calculate the number of rows to sample from Class 0 to achieve 70% Class 1
target_size = int(len(class_1) * 100 / 70) - len(class_1)

# Sample from Class 0 to add to the dataset to make it 70% Class 1
class_0_sample = class_0.sample(n=target_size, random_state=42)

# Combine the sampled data to create the new subset
subset_df = pd.concat([class_1, class_0_sample])

# Shuffle the dataset to ensure randomness
subset_df = subset_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Verify the class distribution
print(subset_df['CloudBurstTomorrow'].value_counts())

CloudBurstTomorrow
1    31877
0    13661
Name: count, dtype: int64

In [ ]:
# Features and target for the subset
X_subset = subset_df.drop(['CloudBurstTomorrow'], axis=1)
y_subset = subset_df['CloudBurstTomorrow']

# Scale the features
X_subset_scaled = scaler.transform(X_subset)  # Use the same scaler to scale

In [ ]:
subset_df

,Location,MinimumTemperature,MaximumTemperature,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,CloudBurstTomorrow,Year,Month,Day,WindGustDirection_sin,WindGustDirection_cos,WindDirection9am_sin,WindDirection9am_cos,WindDirection3pm_sin,WindDirection3pm_cos
0,0.183062,14.600000,22.3,1.5,7.296667,5.977944,30.000000,13.000000,20.0,100.0,...,1,2011,12,19,0.000000,1.000000e+00,0.000000,1.000000e+00,0.000000,1.000000e+00
1,0.217016,9.800000,13.9,0.0,2.022000,5.977944,39.000000,22.000000,24.0,85.0,...,1,2014,9,16,-0.382683,-9.238795e-01,-0.923880,-3.826834e-01,-0.707107,-7.071068e-01
2,0.240540,12.194186,31.7,1.5,5.318667,7.611178,39.837792,13.951313,2.0,95.0,...,0,2010,2,15,-1.000000,-1.836970e-16,0.000000,1.000000e+00,-0.707107,7.071068e-01
3,0.266834,24.700000,30.1,1.5,2.800000,5.977944,43.000000,24.000000,24.0,89.0,...,1,2012,3,12,0.707107,7.071068e-01,1.000000,6.123234e-17,0.923880,3.826834e-01
4,0.188435,12.700000,18.9,1.5,7.296667,5.977944,54.000000,20.000000,9.0,73.0,...,1,2015,12,5,-1.000000,-1.836970e-16,-0.382683,-9.238795e-01,0.382683,-9.238795e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45533,0.269408,-1.100000,2.7,1.5,5.318667,7.611178,50.000000,26.000000,20.0,88.0,...,1,2009,6,8,-0.923880,3.826834e-01,-0.923880,3.826834e-01,-0.923880,3.826834e-01
45534,0.153359,9.900000,23.4,0.0,5.318667,7.611178,28.000000,9.000000,13.0,77.0,...,0,2014,4,16,-1.000000,-1.836970e-16,0.707107,7.071068e-01,-0.923880,3.826834e-01
45535,0.178132,4.700000,22.0,0.0,2.022000,8.900000,20.000000,11.000000,13.0,73.0,...,0,2011,5,21,1.000000,6.123234e-17,0.923880,-3.826834e-01,1.000000,6.123234e-17
45536,0.193752,13.700000,21.4,0.2,5.318667,7.611178,37.000000,13.000000,15.0,69.0,...,1,2012,3,7,-0.382683,-9.238795e-01,-0.707107,-7.071068e-01,-0.707107,-7.071068e-01
45537,0.153359,5.000000,13.0,0.4,5.318667,7.611178,46.000000,17.000000,24.0,88.0,...,1,2015,6,4,-1.000000,-1.836970e-16,0.382683,9.238795e-01,-0.923880,3.826834e-01

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

# Define early stopping to avoid overfitting
early_stop = EarlyStopping(
    monitor='val_loss',  # Monitor validation loss
    patience=5,          # Number of epochs to wait for improvement
    restore_best_weights=True  # Restore weights from the epoch with the best validation loss
)

# Define the secondary model (same architecture as Model B)
model2 = Sequential([
    Dense(64, activation='relu', input_shape=(X_subset_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile the model
model2.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train the secondary model on the new subset with early stopping
history2 = model2.fit(
    X_subset_scaled, y_subset,
    epochs=50,  # You can tweak this as needed
    batch_size=64,
    validation_split=0.2,
    callbacks=[early_stop],  # Add early stopping callback
    verbose=1
)

Epoch 1/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.7686 - loss: 0.4803 - val_accuracy: 0.8034 - val_loss: 0.4221
Epoch 2/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8013 - loss: 0.4278 - val_accuracy: 0.8052 - val_loss: 0.4140
Epoch 3/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8063 - loss: 0.4175 - val_accuracy: 0.8079 - val_loss: 0.4136
Epoch 4/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8067 - loss: 0.4154 - val_accuracy: 0.8105 - val_loss: 0.4106
Epoch 5/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8110 - loss: 0.4091 - val_accuracy: 0.8126 - val_loss: 0.4029
Epoch 6/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8146 - loss: 0.4068 - val_accuracy: 0.8119 - val_loss: 0.4025
Epoch 7/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8143 - loss: 0.4053 - val_accuracy: 0.8106 - val_loss: 0.4053
Epoch 8/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8135 - loss: 0.4051 - val_accuracy: 0.8130 - val_loss: 0.4020
Epoch 9/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8156 - loss: 0.4016 - val_accuracy: 0.8135 - val_loss: 0.3983
Epoch 10/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8168 - loss: 0.4027 - val_accuracy: 0.8136 - val_loss: 0.4011
Epoch 11/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8177 - loss: 0.3994 - val_accuracy: 0.8131 - val_loss: 0.3997
Epoch 12/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8204 - loss: 0.3967 - val_accuracy: 0.8136 - val_loss: 0.3996
Epoch 13/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8188 - loss: 0.3968 - val_accuracy: 0.8072 - val_loss: 0.4147
Epoch 14/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8225 - loss: 0.3918 - val_accuracy: 0.8158 - val_loss: 0.3967
Epoch 15/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8245 - loss: 0.3921 - val_accuracy: 0.8136 - val_loss: 0.3979
Epoch 16/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8214 - loss: 0.3929 - val_accuracy: 0.8164 - val_loss: 0.4003
Epoch 17/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8221 - loss: 0.3950 - val_accuracy: 0.8175 - val_loss: 0.3946
Epoch 18/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8216 - loss: 0.3930 - val_accuracy: 0.8144 - val_loss: 0.3990
Epoch 19/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8264 - loss: 0.3879 - val_accuracy: 0.8093 - val_loss: 0.4078
Epoch 20/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8228 - loss: 0.3898 - val_accuracy: 0.8180 - val_loss: 0.3956
Epoch 21/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8246 - loss: 0.3873 - val_accuracy: 0.8164 - val_loss: 0.3977
Epoch 22/50
570/570 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8286 - loss: 0.3847 - val_accuracy: 0.8181 - val_loss: 0.3967

In [ ]:
# Evaluate Secondary Model (trained on the subset with 70% ones)
print("Secondary Model Evaluation on Subset Dataset:")
model2_test_loss, model2_test_accuracy = model2.evaluate(X_subset_scaled, y_subset)
print(f"Test Accuracy on Subset: {model2_test_accuracy}")

# Predict on the subset test data
y_pred_subset = (model2.predict(X_subset_scaled) > 0.5).astype(int)

# Classification Report for precision, recall, f1-score on the subset dataset
from sklearn.metrics import classification_report
print("Classification Report for Secondary Model on Subset:")
print(classification_report(y_subset, y_pred_subset))

Secondary Model Evaluation on Subset Dataset:
1424/1424 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8285 - loss: 0.3850
Test Accuracy on Subset: 0.8236417770385742
1424/1424 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step
Classification Report for Secondary Model on Subset:
              precision    recall  f1-score   support

           0       0.76      0.61      0.67     13661
           1       0.84      0.92      0.88     31877

    accuracy                           0.82     45538
   macro avg       0.80      0.76      0.78     45538
weighted avg       0.82      0.82      0.82     45538

In [ ]:
import numpy as np
from sklearn.metrics import classification_report, accuracy_score

# Step 1: Predict with model_50 on the test set
model_50_predictions = model_50.predict(X_test)

# Ensure predictions are of shape (n_samples,) for comparison
model_50_predictions = model_50_predictions.flatten()

# Step 2: Identify false positives (model_50 predicts 1, but true label is 0)
false_positives = (model_50_predictions > 0.5) & (y_test.values == 0)  # Make sure y_test is in the correct format

# Step 3: Run those false positives through model2
model2_predictions = model2.predict(X_test[false_positives])

# Step 4: Replace model_50's incorrect predictions with model2's predictions
model_50_predictions[false_positives] = model2_predictions.flatten()

# Step 5: Evaluate the updated model (with model2 corrections)
updated_accuracy = accuracy_score(y_test, (model_50_predictions > 0.5))
print(f"Updated Test Accuracy: {updated_accuracy}")

# Print classification report for the updated predictions
print("Updated Classification Report:")
print(classification_report(y_test, (model_50_predictions > 0.5)))

910/910 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Updated Test Accuracy: 0.8570741097208855
Updated Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.95      0.91     22717
           1       0.74      0.53      0.62      6375

    accuracy                           0.86     29092
   macro avg       0.81      0.74      0.77     29092
weighted avg       0.85      0.86      0.85     29092